name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize]
  pull_request_target:
     types: [synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
